### ISSUE TITLE
Can't detect sim, can't make phone calls

### ISSUE THREAD

**Issue by etoyz** [meizucustoms/android_kernel_meizu_m1721#10]

**Comment by rtx4d** [comment]
Why do you think this is a kernel problem?
Working fine on AOSPA and LOS.
And, no log = no bug.

**Comment by etoyz** [comment]
> Why do you think this is a kernel problem?
> Working fine on AOSPA and LOS.
> And, no log = no bug.

Sorry，it is my fault，I was introduced to this page by mistake.
